# These are supported funding model platforms

custom: 'https://www.paypal.com/donate?business=S9REMLHZB64NQ&no_recurring=0&item_name=Help+fund+my+college+tuition+and+open-source+work&currency_code=USD'
